Use fast rlp crate
velas/triedb pull request #40
Opened 2023-01-20 14:08 UTC by vldm

-[ ] Currently dependency is in local path
-[ ] We also can avoid copying hashes and nibble vecs, second one can help on short collections, while first probably can slightly improve perfomance on big branches.

Introduce next changes in perfomance
```
     Running benches/compare_backends.rs (target/release/deps/compare_backends-7340992dcd32978b)
Gnuplot not found, using plotters backend
bench get TrieCollection<Mem>
                        time:   [413.91 µs 416.98 µs 420.46 µs]
                        change: [-52.270% -51.735% -51.102%] (p = 0.00 < 0.05)
                        Performance has improved.

bench insert TrieCollection<Mem>
                        time:   [4.6423 ms 4.6650 ms 4.6871 ms]
                        change: [-51.300% -50.890% -50.493%] (p = 0.00 < 0.05)
                        Performance has improved.

```

2023-01-24 08:50 UTC, dj8yfo requested changes

2023-01-24 08:50 UTC, dj8yfo commented on src/lib.rs
> -            let subnode = rlp::encode(node).to_vec();
Пирформанс аптиммзейшн спот

2023-01-27 19:43 UTC, dj8yfo commented on src/rlp/decode.rs
> +        let Ok(h) = fastrlp::Header::decode(buf) else {
requires rust 1.65, please remove, so that it can be merged ASAP

2023-01-27 19:43 UTC, dj8yfo commented on src/rlp/decode.rs
> +}
```
// this variant is a bit more precise.
// Err(conditions report if list is invalid altogether)
// Ok() - reports length of list, which the decision is based upon in outer match
pub(crate) fn count(mut buf: &[u8]) -> Result<usize, fastrlp::DecodeError> {
    let buf = &mut buf;
    let mut count: usize = 0;
    loop {
        if buf.is_empty() {
            break;
        }
        let Ok(h) = fastrlp::Header::decode(buf) else {
            return Err(fastrlp::DecodeError::Custom("header expected"));
        };
        if h.payload_length > buf.len() {
            return Err(fastrlp::DecodeError::InputTooShort);
        }
        buf.advance(h.payload_length);
        count += 1;

    }
    // are empty lists sick? (is empty list a valid case in rlp?)
    Ok(count)
}
```

2023-01-27 19:55 UTC, dj8yfo commented on src/rlp/decode.rs
> +    pub fn fast_decode_with_header(
rename to `decode_with_header` to further optimize reading

2023-01-27 19:56 UTC, dj8yfo commented on src/rlp/decode.rs
> +}
```suggestion
// this variant is a bit more precise imho
// Err(conditions report if list is invalid altogether)
// Ok() - reports length of list, which the decision is based upon in outer match
pub(crate) fn count(mut buf: &[u8]) -> Result<usize, fastrlp::DecodeError> {
    let buf = &mut buf;
    let mut count: usize = 0;
    loop {
        if buf.is_empty() {
            break;
        }
        let Ok(h) = fastrlp::Header::decode(buf) else {
            return Err(fastrlp::DecodeError::Custom("header expected"));
        };
        if h.payload_length > buf.len() {
            return Err(fastrlp::DecodeError::InputTooShort);
        }
        buf.advance(h.payload_length);
        count += 1;

    }
    // are empty lists sick? (is empty list a valid case in rlp?)
    Ok(count)
}
```

2023-01-27 20:38 UTC, dj8yfo commented on src/rlp/mod.rs
> +pub mod old;
somehow old cannot be made non-public
```
pub mod encode;
#[cfg(feature = "old_rlp)")]
pub mod old;

pub use decode::{Decodable, DecodeError as DecoderError};

pub use encode::Encodable;

use crate::merkle::nibble::{NibbleType, NibbleVec};

pub use encode::encode;

pub use decode::decode;

#[cfg(feature = "old_rlp)")]
mod testing {

    //!
    //! Implement marker traits for types that Decodable both from regular rlp, and from fastrlp.
    //! Usefull when need to test that both implementation has same output.
    //!

    trait Decodable<'a>: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
    impl<T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}

    trait Encodable: crate::rlp::Encodable + crate::rlp::old::Encodable {}
    impl<T> Encodable for T where T: crate::rlp::Encodable + crate::rlp::old::Encodable {}
}

#[derive(Eq, PartialEq, Debug)]
pub struct NibblePair(pub NibbleVec, pub NibbleType);

#[cfg(test)]
mod tests {
    use crate::merkle::nibble::Nibble;
    use crate::merkle::{Branch, Extension, Leaf, MerkleNode, MerkleValue};
    use crate::{
        merkle::nibble::{self, NibbleType},
        rlp,
    };
    use hexutil::read_hex;
    use primitive_types::H256;
    use super::old;
```
```
  --> src/rlp/mod.rs:44:9
   |
44 |     use super::old;
   |         ^^^^^^^^^^ no `old` in `rlp`
```

2023-01-27 20:58 UTC, dj8yfo commented on Cargo.toml
> +rlp_old = {version= "0.5.0", package="rlp", optional = true}
Rename to old_rlp to remove indirection below?

2023-01-28 09:37 UTC, dj8yfo commented
Please also consider removing `where Self: 'de` in fastrlp fork

2023-01-28 17:42 UTC, dj8yfo requested changes
After applying diff `old_rlp)` -> `old_rlp`
```
diff --git a/src/rlp/mod.rs b/src/rlp/mod.rs
index a18a1a5..cfe4e45 100644
--- a/src/rlp/mod.rs
+++ b/src/rlp/mod.rs
@@ -1,6 +1,6 @@
 pub mod decode;
 pub mod encode;
-#[cfg(feature = "old_rlp)")]
+#[cfg(feature = "old_rlp")]
 pub mod old;
 
 pub use decode::{Decodable, DecodeError as DecoderError};
@@ -13,7 +13,7 @@ pub use encode::encode;
 
 pub use decode::decode;
 
-#[cfg(feature = "old_rlp)")]
+#[cfg(feature = "old_rlp")]
 mod testing {
 
     //!
@@ -44,10 +44,10 @@ mod tests {
 
     macro_rules! check_roundtrip {
         ($v: expr => $type: ty) => {{
-            #[cfg(feature = "old_rlp)")]
+            #[cfg(feature = "old_rlp")]
             let old_rlp_raw: Vec<u8>;
             let rlp_raw;
-            #[cfg(feature = "old_rlp)")]
+            #[cfg(feature = "old_rlp")]
             {
                 old_rlp_raw = crate::rlp::old::encode(&$v);
                 dbg!(hexutil::to_hex(&old_rlp_raw));
@@ -61,7 +61,7 @@ mod tests {
                 assert_eq!(decoded_node, $v);
             }
 
-            #[cfg(feature = "old_rlp)")]
+            #[cfg(feature = "old_rlp")]
             {
                 assert_eq!(old_rlp_raw, rlp_raw);
             }
```
got a ton of compilation errors :
```
   Compiling triedb v0.5.0 (/home/jerryminion/Documents/code/study/rust/solana-slash-velas/triedb_raventid)
error[E0432]: unresolved import `super::NibblePair`
 --> src/rlp/old/decode.rs:7:5
  |
7 | use super::NibblePair;
  |     ^^^^^^^^^^^^^^^^^ no `NibblePair` in `rlp::old`

error[E0432]: unresolved import `super::NibblePair`
 --> src/rlp/old/encode.rs:6:5
  |
6 | use super::NibblePair;
  |     ^^^^^^^^^^^^^^^^^ no `NibblePair` in `rlp::old`

error[E0261]: use of undeclared lifetime name `'a`
  --> src/rlp/old/decode.rs:24:19
   |
24 | impl<T> Decodable<'a> for T
   |      -            ^^ undeclared lifetime
   |      |
   |      help: consider introducing lifetime `'a` here: `'a,`

error[E0261]: use of undeclared lifetime name `'a`
  --> src/rlp/mod.rs:25:23
   |
25 |     impl<T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |          -            ^^ undeclared lifetime
   |          |
   |          help: consider introducing lifetime `'a` here: `'a,`

error[E0261]: use of undeclared lifetime name `'a`
  --> src/rlp/mod.rs:25:64
   |
25 |     impl<T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |                                                                ^^ undeclared lifetime
   |
   = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
   |
25 |     impl<T> Decodable<'a> for T where T: for<'a> crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |                                          +++++++
help: consider making the bound lifetime-generic with a new `'a` lifetime
   |
25 |     impl<T> Decodable<'a> for T where for<'a> T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |                                       +++++++
help: consider introducing lifetime `'a` here
   |
25 |     impl<'a, T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |          +++

error[E0261]: use of undeclared lifetime name `'a`
  --> src/rlp/mod.rs:25:97
   |
25 |     impl<T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |                                                                                                 ^^ undeclared lifetime
   |
help: consider making the bound lifetime-generic with a new `'a` lifetime
   |
25 |     impl<T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + for<'a> crate::rlp::old::Decodable<'a> {}
   |                                                                      +++++++
help: consider making the bound lifetime-generic with a new `'a` lifetime
   |
25 |     impl<T> Decodable<'a> for T where for<'a> T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |                                       +++++++
help: consider introducing lifetime `'a` here
   |
25 |     impl<'a, T> Decodable<'a> for T where T: crate::rlp::Decodable<'a> + crate::rlp::old::Decodable<'a> {}
   |          +++

warning: unused imports: `NibbleType`, `NibbleVec`
 --> src/rlp/old/mod.rs:7:29
  |
7 | use crate::merkle::nibble::{NibbleType, NibbleVec};
  |                             ^^^^^^^^^^  ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0592]: duplicate definitions with name `inlinable`
  --> src/rlp/decode.rs:54:5
   |
54 |     pub fn inlinable(&self) -> bool {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `inlinable`
   |
  ::: src/rlp/old/encode.rs:14:5
   |
14 |     pub fn inlinable(&self) -> bool {
   |     ------------------------------- other definition for `inlinable`

Some errors have detailed explanations: E0261, E0432, E0592.
For more information about an error, try `rustc --explain E0261`.
warning: `triedb` (lib) generated 1 warning
error: could not compile `triedb` due to 7 previous errors; 1 warning emitted
```
Please either remove `old_rlp` or make it compile.

2023-01-28 17:45 UTC, dj8yfo commented on src/rlp/mod.rs
> +pub mod old;
please make it non-`pub`

2023-03-09 14:26 UTC, Tirka commented
Bump crate to version `0.6.0` after merge?

2023-03-10 20:32 UTC, dj8yfo approved these changes

2023-03-15 14:05 UTC, merged